#!/usr/bin/env bash

# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 

# Usage: dxmaketree [-b]
#
# Build the entire project tree that is rooted at the current working
# directory. Do this by calling all makeme scripts in the tree. By
# default, the makeme scripts are called through a top-down traversal
# of the tree 
# (higher level directories have their
# makeme scripts executed before their respective subdirectories).
# If the -b option is used, then a bottom-up directory traversal
# is performed instead.
#
# Directories that do not have makeme files are silently ignored during the
# top-down or bottom-up traversal.

# Default option
dxtrex_opt=""

while getopts ":b" opt; do
    case $opt in
    b ) dxtrex_opt="-b" ;;
    \? ) echo 'usage: dxmaketree [-b]' 
         exit 1
    esac
done
shift $(($OPTIND - 1))

dxtrex $dxtrex_opt dxmaketree_core
