#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################

# A standard configuration for setting up DICE lang OpenCL (DLOCL). 
# This script needs to be sourced.
 
# Make sure all setting are exported into subprocesses.
set -a

# Define environment variables for using DLOCL features

# Location of the DLOCL installation
UXDLOCL=$UXDICELANG/ocl

# DLOCL directory for files that are generated from DLOCL source code files
DLOCLGEN=$DLXGEN/ocl

# Make sure required directories exist in the gen tree
dx_ensure_dir $DLOCLGEN
dx_ensure_dir $DLOCLGEN/util

# Location of include files for DLOCL utilities library
DLOCLUTILINC=$UXDLOCL/src/util

# Incorporate LANG-OCL-related PATH extensions 
source $UXDLOCL/config/startup/pathsetup

# Incorporate LANG-OCL-related utility functions 
source $UXDLOCL/config/startup/utils
