#!/usr/bin/env bash

#############################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
#############################################################################

# @author Chung-Ching Shen and Shuvra S. Bhattacharyya 

# A standard configuration file for setting up DICE lang. 
# This script needs to be sourced.

# Make sure all setting are exported into subprocesses.
set -a

###############################################################################
# Check for existence of required variable settings
###############################################################################

# Before sourcing this script, the UXDICELANG variable should be
#ddefined to point to the active dice lang installation.

if [ -z "$UXDICELANG" ]; then
    echo dicelang startup error: UXDICELANG variable not defined
    exit 1
fi

###############################################################################
# Check for existence of required variable settings
###############################################################################

# Define the DICE lang user directory and make sure it exists

if [ -z "$DLXUSER" ]; then
    echo "dicelang startup error: DLXUSER variable is undefined."
    exit 1
fi
dx_ensure_dir $DLXUSER

# The directory for installing files that are generated from dicelang source
# code
if [ -z "$DLXGEN" ]; then
    DLXGEN=$DLXUSER/dlxgen
fi
dx_ensure_dir $DLXGEN

###############################################################################
# Source language-specific configuration files
###############################################################################
function dlx_startuplang {
    if [ -d $UXDICELANG/$1 ]; then
        dxsource $UXDICELANG/$1/config/startup/standard_startup
    fi
}

# Note: language-specific user directories are presently not used.
# If a language requires a separate user directory, one needs to
# put something like this (example for DLC) in the language-specific startup 
# file:
# DLCUSER=$DLXUSER/c
# dx_ensure_dir $DLCUSER

# Features that are common across languages. This should be loaded FIRST.
dlx_startuplang common

# ANSI C
dlx_startuplang c

# OpenCL
dlx_startuplang ocl 

# LaTeX
dlx_startuplang latex 
