#!/usr/bin/env bash

############################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
############################################################################

# A standard configuration for setting up DICEMIN. In this setup, 
# a directory called dice_user 
# is assumed to exist; the value of DXUSER should be set to the path
# of this dice_user directory before entering this script.
#
# This script needs to be sourced.
 
# Make sure all setting are exported into subprocesses.
set -a

# Make sure that the given directory exists
function dx_ensure_dir {
    if [ -z "$1" ]; then
        echo dx_ensure_dir error: missing argument
        return 1;
    fi
    if [ -f "$1" ]; then
        echo dx_ensure_dir error: cannot make directory \"$1\" because
        echo ... there is already a file with the same name.
        echo ... the path is `pwd`
        return 1
    elif ! [ -d "$1" ]; then
        mkdir "$1"
        if [ $? -ne 0 ]; then
            echo dx_ensure_dir error: could not find nor make directory $1 
            echo ... the path is `pwd`
            return 1
        fi
        cd "$1"
        touch README.txt
        echo >> README.txt
        echo Required directory ... >> README.txt
        echo created by dx_ensure_dir on `date` . >> README.txt
        cd ..
    fi
}

###############################################################################
# dxsource
# Usage: dxsource <script> [<args>]
# Source a script with any number of arguments. 
# Before and after the script is sourced, echo
# a status message. Enable these status messages only if $DXVERBOSE
# is non-null.
#
# For better diagnostics (with the status messages), it is best if
# the full path of <script> is passed as the argument to this fuction.
#
# The DXVERBOSE variable guards the display of diagnostic messages.
# If this variable is not set or null-valued, then diagnostic display
# is suppressed.
###############################################################################
function dxsource {
    if [ -z "$1" ]; then
        echo dxsource error: Missing argument
    fi
   
    dx_diagnostic dxsource: starting $1 from `pwd`
    source $*
    dx_diagnostic dxsource: finished with $1 from `pwd`
}

# Make sure the dice user variable set
if [ -z "$DXUSER" ]; then
    echo "DICEMIN startup error: DXUSER variable is undefined."
    exit 1
fi

# Make sure the dicemin installation variable is set
if [ -z "$UXDICEMIN" ]; then
    echo "DICEMIN startup error: UXDICEMIN variable is undefined."
    exit 1
fi

# The directory for installing files that are generated from 
# source code files in dicemin. If this variable already set, then
# use the original setting. The variable would be set previously,
# for example, if installed files are being provided from 
# a common/shared directory.
if [ -z "$DXMGEN" ]; then
    DXMGEN=$DXUSER/dxmgen
fi

# Standard directory for storing DICE-related temporary files.
if [ -z "$UXTMP" ]; then
    UXTMP=$DXUSER/tmp
fi


################################################################################
# Make sure required directories exist
################################################################################
dx_ensure_dir $DXUSER
dx_ensure_dir $DXMGEN
dx_ensure_dir $UXTMP

################################################################################
# Incorporate DICE-related PATH extensions into the path
################################################################################
dxsource $UXDICEMIN/config/startup/pathsetup

################################################################################
# Load utility functions for DICEMIN
################################################################################
dxsource $UXDICEMIN/scripts/dxmutils

