#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2018
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################

# A standard configuration file for setting up LIDE. 
# This script needs to be sourced.

# Make sure all setting are exported into subprocesses.
set -a

###############################################################################
# Check for existence of required variable settings
###############################################################################

# Before sourcing this script, the UXLIDE variable should be
# defined to point to the active LIDE installation.

if [ -z "$UXLIDE" ]; then
    echo LIDE startup error: UXLIDE variable not defined
    exit 1
fi

###############################################################################
# Check for existence of required variable settings
###############################################################################

# Define the LIDE user directory and make sure it exists

if [ -z "$LIDEUSER" ]; then
    echo "LIDE startup error: LIDEUSER variable is undefined."
    exit 1
fi
dx_ensure_dir $LIDEUSER

# The directory for installing files that are generated from LIDE source
# code
dxpushd "$LIDEUSER"/startup
if [ -f lidegen.txt ]; then
    LIDEGEN=`cat ./lidegen.txt`
elif [ -z "$LIDEGEN" ]; then
    LIDEGEN="$LIDEUSER"/lidegen
fi
dxpopd

echo "$LIDEUSER"
echo "$LIDEGEN"
dx_ensure_dir $LIDEGEN

###############################################################################
# Source language-specific configuration files
###############################################################################
function lide_startuplang {
    if [ -d "$UXLIDE"/lang/"$1" ]; then
       dxsource "$UXLIDE"/lang/"$1"/config/startup/standard_startup
    fi
}

################################################################################
# Incorporate LIDE-related PATH extensions into the path
################################################################################
dxsource $UXLIDE/config/startup/pathsetup

################################################################################
# Load sub-packages
################################################################################

dxpushd "$UXLIDE"/scripts/bash/common
if [ -f ./load_subpacks ]; then
    dxsource ./load_subpacks
fi
dxpopd

# The following LIDE plug-ins are loaded if present. This list should be
# maintained in ALPHABETICAL ORDER (after "common"), which should be loaded
# first.

# LIDE-Android
lide_startuplang android

# LIDE-C 
lide_startuplang c

# LIDE-OCL
lide_startuplang ocl
