#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################

# A standard configuration for setting up DICE. In this setup, 
# a directory called dice_user 
# is assumed to exist; the value of DXUSER should be set to the path
# of this dice_user directory before entering this script.
#
# This script needs to be sourced.
 
# Make sure all setting are exported into subprocesses.
set -a

# See if there is a local startup file for DICE, and execute it if
# there is one
if [ -f $UXDICE/../dice_local/localstartup ]; then
    dxsource $UXDICE/../dice_local/localstartup
fi

# Conventions under standard DICE setup
UXGO=$DXUSER/g
UXGU=$DXUSER/gu
UXCLIPBOARD=$UXTMP/clipboard

# The directory for installing files that are generated from 
# source code files in dice. If this variable already set, then
# use the original setting. The variable would be set previously,
# for example, if installed files are being provided from 
# a common/shared directory.
if [ -z "$DXGEN" ]; then
    DXGEN=$DXUSER/dxgen
fi

# Make sure required directories exist
dx_ensure_dir $DXUSER
dx_ensure_dir $UXGO
dx_ensure_dir $UXGU
dx_ensure_dir $DXGEN
dx_ensure_dir $UXCLIPBOARD

################################################################################
# Incorporate DICE-related PATH extensions into the path
################################################################################
dxsource $UXDICE/core/config/startup/pathsetup

################################################################################
# Load sub-packages
################################################################################

dxpushd "$UXDICE"/core/scripts/bash/common
if [ -f ./load_subpacks ]; then
    dxsource ./load_subpacks
fi
dxpopd

dxpushd "$UXDICE"/core/scripts/bash/common/dicedoc
if [ -f ./load_subpacks ]; then
    dxsource ./load_subpacks
fi
dxpopd

# Load DICE utilities
dxsource $UXDICE/core/config/startup/setuputils $UXARCH
dxsource $UXDICE/core/scripts/bash/common/diceutils


