#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
################################################################################

# Utility functions for DLC

# Display the current dlc project configuration.
function dlcprojshow {
    echo -DLC Project Configuration:-
    echo -each variable value is shown between a pair of dashes- 
    echo ----------------------------
    echo dlcincludepath=-$dlcincludepath-
    echo dlclibpath=-$dlclibpath-
    echo dlcmklibs=-$dlcmklibs-
    echo dlctargetfile=-$dlctargetfile-
    echo dlcinstalldir=-$dlcinstalldir-
    echo dlcobjs=-$dlcobjs-
    echo dlcverbose=-$dlcverbose-
    echo ----------------------------
}

# Reset the current dlc project configuration: that is, set the values
# of all project variables to the null string.
function dlcprojreset {
    dlcincludepath=""
    dlclibpath=""
    dlcmklibs=""
    dlctargetfile=""
    dlcinstalldir=""
    dlcobjs=""
    dlcverbose=""
}

