#!/usr/bin/env bash

# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 

# BASH utilities for DICE

# Silent version of pushd: don't echo information about the status of the 
# directory stack.
function dxpushd {
    pushd $@ > $UXTMP/dxpushd_discard.txt
}

# Silent version of popd: don't echo information about the status of the 
# directory stack.
function dxpopd {
    popd $@ > $UXTMP/dxpopd_discard.txt
}

###############################################################################

# Validate the last command that was executed. This function checks the
# return value from the most recent command that was executed. If the
# return value is nonzero, then the function exits with an error message.
# The error message is composed by taking all of the arguments to the function.
#
# Usage example:
# 
# mkdir tmp
# dxvalidate could not create tmp directory
function dxvalidate {
    if [ $? -ne 0 ]; then
        echo $@
        exit 1
    fi
} 

