#!/usr/bin/env bash

# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 

# Dos to unix file format conversion for the current working directory 
#
# Usage dxdtud extension>
#
# Naming: Stands for (D)OS (T)o (U)nix conversion for a (D)irectory 
#
# This script processes the current working directory, and converts selected
# text files to unix format. In particular, text files whose names have
# extensions that match the given extension are converted.
# If the script argument is the null string (""), then only text files that
# have extension-less names are converted.
#
# Binary files are always bypassed (not converted)
#
# If "all" is specified as the extension, then all text files are converted.
#
# Example usage: dxdtud bash 
#                dxdtud all 
#                dxdtud txt
#                dxdtud ""
#

# We can't use dx_check_arg because we allow a null-string argument
if [ $# -ne 1 ]; then
    echo dxdtud: arg count
    exit 1
fi

DXDIEX_ARGS=""
dxdiex dxdtuf "$1" "false"


