#!/usr/bin/env bash

#############################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
#############################################################################

# Copy an item from the DICE installation directory to the current
# working directory. Selected items from the DICE installation
# directory are available to copy in a convenient way using
# this utility.

# Usage: dxget <item identifier>:

lxprog=dxget
lxitem=""
lxfile=""
lxfilebase=""

if [ $# -ne 1 ]; then
    echo $lxprog error: arg count
    exit 1
fi
lxitem="$1"

if [ "$lxitem" = help ]; then
    echo $lxprog choices:
    echo "    dice-intro-presentation"
    echo "    basicocl"
    exit 0
elif [ "$lxitem" = dice-intro-presentation ]; then
    lxfile="$UXDICE/doc/dice-intro-presentation.pdf"
elif [ "$lxitem" = basicocl ]; then
    lxfile="$UXDICE/lang/ocl/demo/opencl_device_check"
else
    echo $lxprog error: invalid template choice --- \"$lxitem\"
    exit 1
fi

if ! [ -a "$lxfile" ]; then
    echo $lxprog: $lxfile does not exist
    exit 1
fi

lxfilebase=`basename "$lxfile"`
if [ -a "$lxfilebase" ]; then
    echo $lxprog: ./$lxfilebase already exists
    exit 1
fi

echo $lxprog: copying template \"$lxfile\" ...
dxcp $lxfile .
