#!/usr/bin/env bash

#############################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
#############################################################################

#The utility should unpack the contents of the specified archive (if the 
#specified file is an archive) an move the unpacked files to the appropriate 
#directory/directories within $UXDICE (the current dice installation). 
#If the specified plug-in is in the form of a single file (not .tar.gz) 
#then it could just move that single file.

# Usage: dxinstall <item identifier>:

lxprog=dxinstall
lxitem=""
lxfile=""
lxdst=""
lxsrc=""
lxdstfile=""

if [ $# -ne 1 ]; then
    echo $lxprog error: arg count
    exit 1
fi

lxitem="$1"

if [ "$lxitem" = help ]; then
    echo $lxprog choices:
    echo "    dice-android.tar.gz"
    echo "    dice-android"
    exit 0
elif [ "$lxitem" = dice-android ]; then
    lxfile="$lxitem"
    lxdst="$UXDICE/lang/ocl/"
    lxsrc="./$lxfile/snapdragon"
elif [ "$lxitem" = dice-android.tar.gz ]; then
    dxunpack ./"$lxitem"
    lxfile=${lxitem%.tar.gz}
    lxdst="$UXDICE/lang/ocl/"
    lxsrc="./$lxfile/snapdragon"
else
    echo $lxprog error: invalid installation item choice --- \"$lxitem\"
    exit 1
fi

if ! [ -a "$lxsrc" ]; then
    echo $lxprog: $lxfile does not exist
    exit 1
fi

if [ "$lxitem" = dice-android ] || [ "$lxitem" = dice-android.tar.gz ]; then
    lxdstfile=$lxdst
    lxdstfile+="snapdragon"
    if [ -a "$lxdstfile" ]; then
        echo $lxprog: $lxdstfile already exists
        exit 1
    fi
fi

echo $lxprog: install \"$lxfile\" to DICE...
dxcp "$lxsrc" "$lxdst"
