#!/usr/bin/env bash

###############################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
###############################################################################

# @ddblock_begin doc
# Extract a tar.gz archive. Remove the intermediate .tar file that
# results from the extraction process.
# @ddblock_end doc

DXPROG=dxunpack
source dx_check_arg

name=`basename "$1" .tar.gz`
if ! [ -f "$name".tar.gz ]; then
    echo dxunpack error: "$name".tar.gz does not exist
    exit 1
fi

if [ -a "$name" ]; then
    echo dxunpack error: A file or directory called "$name" already exists
    exit 1
fi


# The following slightly long-winded version is more portable.
gunzip "$name".tar.gz
tar xf "$name".tar

# Clean up
rm -f "$name".tar

