#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
################################################################################

################################################################################
# DICE utility (dx) for (v)a(l)i(d)ating (arch)itecture [platform] specifiers
# (i.e., settings of UXARCH)
# 
# Validate the user specified architecture/platform argument (\ddcode{UXARCH}).
#
# Usage: dxvldarch <platform>
#
# Usage example: dxvldarch win
#
# Valid platform arguments are lin, macos, sol, win.
#
# This utility returns \ddcode{valid} if <platform> is one of the valid
# platform settings listed above. Othwerwise, the utility returns 
# \ddcode{invalid}.
#
################################################################################

# Export definitions to sub-processes
set -a

lxprog="dxvldarch"

if [[ $# -ne 1 ]]; then
    echo "$lxprog" error: arg count
    exit 1
fi

if [[ ("$1" == win) || ("$1" == sol) || ("$1" == lin) 
        || ("$1" == macos) ]]; then
    echo valid
else 
    echo invalid
fi



