#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2018
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################
# Script to configure this project

dlcincludepath="-I. -I$UXLIDEC/src/gems/actors/communication/common \
-I$UXLIDEC/src/gems/actors/basic -I$UXLIDEC/src/gems/actors/common \
 -I$UXLIDEC/src/gems/edges/basic -I$UXLIDEC/src/tools/runtime"
dlcmiscflags=""
dlclibpath=""
dlclibs="$LIDECGEN/lide_c_basic.a $LIDECGEN/lide_c_runtime.a \
$LIDECGEN/lide_c_communication_common.a -lm -Q"
dlctargetfile="lide_c_communication_channel_estimation.a"
dlcinstalldir="$LIDECGEN"
dlcobjs="lide_c_auto_correlation_computation.o lide_c_coefficient_computation.o \
lide_c_cross_correlation_computation.o lide_c_matrix_inversion.o \
lide_c_noise_adder.o lide_c_response_computation.o"
dlcverbose=""
