#!/usr/bin/env bash


#############################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
#############################################################################

# Usage: source dlcmakeme <no arguments>

# This script needs to be sourced.

#############################################################################
# Load the dlc project configuration
#############################################################################

# Clear out any previous configuration. This helps in avoiding
# hard-to-track bugs due to settings that creep in from previously
# processed projects.
dlcprojreset

source ./dlcconfig

if [ -n "$dlcverbose" ]; then
    echo dlcmakeme, displaying project configuration:
    dlcprojshow 
fi

#############################################################################
# Figure out which build command to be executed
#############################################################################
if [ -z "$dlc_build_command" ]; then
    source "$UXDICE"/lang/c/scripts/dlc_build_default
else
    if [ -n "$dlcverbose" ]; then
        echo dlcmakeme, executing: $dlc_build_command
    fi
	source $dlc_build_command
    if [ $? -ne 0 ]; then
        echo dlcmakeme: error encountered when executing ...
        echo build command \"$dlc_build_command\"
    fi
fi

