#!/usr/bin/env bash

# @ddblock_begin copyright 
#
# Copyright (c) 1999-2014
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
# All rights reserved.

# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# @ddblock_end copyright 

# bash wrapper for C script dxext.exe, which replaces the python
# script dxext.py. Also, this bash wrapper (along with the C script)
# has been moved from dice/plus/scripts/bash to dice/min/scripts. This
# is to eliminate circular dependencies with the script
# dlcmakeme. This reorganization makes dxext C script independent of
# dicelang-c.

lxprog=dxext
if [ $# -eq 0 ]; then
    echo $lxprog error: arg count 1>&2
    exit 1
fi

if [ $# -gt 2 ]; then
    echo $lxprog error: arg count 1>&2
    exit 1
fi

dxextcore.exe "$@"

if [ $? -ne 0 ]; then
    echo $lxprog error: nonzero return status from core program dxext.exe 1>&2
    exit 1 
fi
