#!/usr/bin/env bash

############################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
############################################################################

# Wrapper script for removing carriage return characters from a file.
# This script can be used, for example, to convert a text file from
# DOS format to UNIX format.

if [ $# -ne 1 ]; then
    echo dxrmcr error: arg count
    exit 1
fi

# Copy the specified file to a temporary file so that temporary file
# has same file permissions as the specified file. Otherwise, some of
# the file permissions may be lost when "mv" is executed at the end.
cp "$1" dxrmcrcore-tmp.txt
dxrmcrcore.exe "$1" dxrmcrcore-tmp.txt
if [ $? -ne 0 ];  then
    echo dxrmcr error: core processing failed
    exit 1
fi
mv dxrmcrcore-tmp.txt "$1"
if [ $? -ne 0 ];  then
    echo dxrmcr error: could not replace original file
    exit 1
fi

