#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################

################################################################################
# This script is to set up LIDE using version in lidepub
# repository
# 
# Usage format: source setup/setup
# Working directory: lidepub/lide directory
#
# If $LIDEUSER are not set, the default value would be set
# By default, LIDEUSER=~/dspcad_user/lide_user; 
#
################################################################################


# Export definitions to sub-processes for lide setup

set -a

UXLIDE="$(pwd)"

# check whether the current working direcory is the lide directory
if [ ! -f "$UXLIDE"/setup/setup ] || [[ "$UXLIDE" != *"lide" ]]; then
    echo setup error: setup should be performed from the top-level directory
    echo "(lide) of the lide installation"
    exit 1
fi

# if LIDEUSER are not set, default path would be set here
# default: path of lide_user is in ~/dspcad_user/lide_user

pushd ~
if [[ -z "$LIDEUSER" ]]; then    
    mkdir -p dspcad_user
    cd dspcad_user
    mkdir -p lide_user
    LIDEUSER=~/dspcad_user/lide_user
fi
popd

# setup LIDE
pushd "$LIDEUSER"
cd ..
echo Starting to set up LIDE ...
echo ----------------------------
source "$UXLIDE"/setup/runme
echo ----------------------------
echo Setup of LIDE is complete

popd
