#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright  
################################################################################ 

# DLOCL standard script to install a project.

# Usage: dloclinstallme <no arguments>

# If the project configuration does not specify an installation directory,
# then a warning message is displayed and the installation request
# is ignored (nothing is installed).

#dlxconfigure dlcconfig
dlxconfigure dloclconfig

if [ $? -ne 0 ]; then
    exit
fi

if [ -z "$dloclinstalldir" ]; then
    echo dloclinstall: No installation directory associated with `pwd`
    echo Nothing installed from `pwd`
    exit 0
fi

if ! [ -f ./$dlocltargetfile ]; then
    echo dloclinstallme error: target file $dlocltargetfile not found
    exit 1
fi

cp ./$dlocltargetfile $dloclinstalldir