#!/usr/bin/env bash

#############################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
#############################################################################

# Usage: dloclmakeme <no arguments>

#############################################################################
# Load the dlocl project configuration
#############################################################################

source ./dloclconfig

#############################################################################
# Figure out which build command to be executed
#############################################################################

# Check Operating System
MACH=`uname -m`

# Configure C/C++ flag if target is Android
if [ "$dlocl_build_command" == "dlocl_build_android" ]; then
    #CC=arm-linux-androideabi-$dloclcompiler
    OCL_FGI="-I $UXDICE/lang/ocl/snapdragon/include"
    OCL_FGL="-L $UXDICE/lang/ocl/snapdragon/lib -lOpenCL -fPIE -pie"
    OCL_FG=""

# Configure C/C++ flag if host is Mac
elif [ "$UXARCH" == "macos" ]; then
    OCL_FGI=""
    OCL_FGL="-framework OpenCL"
    OCL_FG=""

# Configure C/C++ flag if host is Linux x86 with AMD OpenCL SDK
elif [ "$UXARCH" == "lin" ] && [ "$AMDAPPSDKROOT" != "" ] && \
    [ "$MACH" == "x86_64" ]; then
    OCL_FGI="-I $AMDAPPSDKROOT/include" 
    OCL_FGL="-L $AMDAPPSDKROOT/lib/x86_64"
    OCL_FG="-lOpenCL"

# Configure C/C++ flag if host is Linux x64 with AMD OpenCL SDK
elif [ "$UXARCH" == "lin" ] && [ "$AMDAPPSDKROOT" != "" ] && \
    [ "$MACH" == "x86" ]; then
    OCL_FGI="-I $AMDAPPSDKROOT/include"
    OCL_FGL="-L $AMDAPPSDKROOT/lib/x86"
    OCL_FG="-lOpenCL"

# Configure C/C++ flag if host is Linux x64 with NVidia OpenCL SDK
elif [ "$UXARCH" == "lin" ] || [ "$NVSDKCOMPUTE_ROOT" != "" ]; then
    OCL_FGI="-I $NVSDKCOMPUTE_ROOT/OpenCL/common/inc"
    OCL_FGL=""
    OCL_FG="-lOpenCL"

else
 echo $lxprog error: invalid host \"UXARCH\" or there is no OpenCL SDK
 exit
fi
 
dlcincludepath="$dloclincludepath $OCL_FGI"
dlclibpath="$dlocllibpath $OCL_FGL"
dlclibs="$dlocllibs"
dlctargetfile="$dlocltargetfile"
dlcinstalldir="$dloclinstalldir"
dlcobjs="$dloclobjs"
dlcverbose="$dloclverbose"
dlcmiscflags="$dloclmiscflags"
dlcmiscldflags="$dloclmiscldflags"