#!/usr/bin/env bash


#############################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
#############################################################################

# Usage: source dlocl_build_android

# This script needs to be sourced.


#############################################################################
# Set compiler and compiling flags for android
#############################################################################
OCL_FGI="-I $UXDICE/lang/ocl/snapdragon/include"
OCL_FGL="-L $UXDICE/lang/ocl/snapdragon/lib -lOpenCL -fPIE -pie"
OCL_FG=""

#############################################################################
# Figure out which top-level makefile to include
#############################################################################

dloclextension=`dxext $dlocltargetfile`

if [ -z "$dloclextension" ]; then
    echo dloclmakeme error:  missing target file extension
    exit 1
fi

if [ "$dloclextension" == exe ] && [ "$dloclcompiler" == "gcc" ]; then
    dloclmakefile=$UXDICE/lang/ocl/config/proj/c_exe.mk
elif [ "$dloclextension" == a ] && [ "$dloclcompiler" == "gcc" ]; then
    dloclmakefile=$UXDICE/lang/ocl/config/proj/c_lib.mk
elif [ "$dloclextension" == exe ] && [ "$dloclcompiler" == "g++" ]; then
    dloclmakefile=$UXDICE/lang/ocl/config/proj/cpp_exe.mk
elif [ "$dloclextension" == a ] && [ "$dloclcompiler" == "g++" ]; then
    dloclmakefile=$UXDICE/lang/ocl/config/proj/cpp_lib.mk
else
    echo dloclmakeme error: invalid makefile extension $dloclextension
    exit 1
fi


#############################################################################
# Compile the project
#############################################################################

if [ -n "$dloclverbose" ]; then
    echo dloclmakeme, executing: make -f $dloclmakefile
fi

CC=arm-linux-androideabi-$dloclcompiler
AR=arm-linux-androideabi-ar
#statements
make CC=$CC AR=$AR -f $dloclmakefile
