#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################

# This script should be sourced.

###############################################################################
# Function ddsetcpr
#
# Set the UXCOPYRIGHT environment variable so that it points to
# the current working directory
#
# Usage dxsetcpr <no arguments>
#
# This script is useful, especially in conjunction with the dlk and g
# utilities, to switch efficiently among different copyright directories.
#
function ddsetcpr {
    UXCOPYRIGHT=`pwd`
}

###############################################################################
# Function ddshowcpr
#
# Show the current value of the UXCOPYRIGHT variable, which
# points to the directory from which ddputcpr and related utilities
# take copyright headers. 
#
# Usage ddshowcpr <no arguments>
#
# This script has been modified to use dxvar_get utility.
function ddshowcpr {
    local lxprog=ddshowcpr

    if [ -z "$UXCOPYRIGHT" ]; then
        echo "$lxprog" error: no copyright path is currently defined
        return 1
    fi

    echo $UXCOPYRIGHT
}
